[tox]
env_list = py313, lint, type, lint-docs, lint-yaml
min_version = 4.0

[testenv]
description = Run unit tests
package = skip
deps =
    -r requirements_dev.txt
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest -q

[testenv:lint]
description = Run Python lint checks
deps =
    -r requirements_dev.txt
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    flake8 src test
    pylint src/offsite

[testenv:type]
description = Run static typing checks
deps =
    -r requirements_dev.txt
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    mypy src

[testenv:lint-docs]
description = Run Markdown lint checks
deps =
    -r requirements_dev.txt
commands =
    pymarkdown --config .pymarkdown.json scan README.md

[testenv:lint-yaml]
description = Run YAML lint checks
deps =
    -r requirements_dev.txt
commands =
    yamllint .github
